import requests
import binascii
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
import warnings
import threading
import my_pb2
#*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\"\x13\n\x05Items\x12\n\n\x02id\x18\x01 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMS._serialized_start=12
  _ITEMS._serialized_end=31
# @@protoc_insertion_point(module_scope)


warnings.filterwarnings("ignore", message="Unverified HTTPS request")

# المفاتيح الثابتة للتشفير
key = "Yg&tc%DEuh6%Zc^8".encode()
iv = "6oyZDr22E3ychjM%".encode()

# قائمة العناصر المراد إرسالها
items_to_send = [
    913033001, 910039002, 910040002, 910035002, 910035001,
    910032003, 910033003, 910034001, 910033001, 910033002,
    910031009, 910031010, 910032001, 910031008, 1001000006,
    910031005, 910031005, 910031007, 910031006, 910031004,
    910030002, 910031001, 910002901, 910030001, 910000004,
    910000006, 910000005, 910000008, 1001000020910000007, 910000010,
    910000009, 910000012, 910000011, 910000013, 1001000026,
    910002801, 910000001, 1001000029, 1001000030, 1001000031,
    1001000032, 1001000033, 1001000034, 1001000035, 1001000036,
    1001000037, 1001000038, 1001000039, 1001000040, 1001000041,
    1001000042, 1001000043, 1001000044, 1001000045,801000020, 801000015, 801000016, 827001001, 801000213,
    801000144, 801000140, 801000139, 801000089
]

# وظيفة لتشفير البيانات باستخدام AES
def encrypt_aes(hex_data):
    cipher = AES.new(key, AES.MODE_CBC, iv)
    padded_data = pad(bytes.fromhex(hex_data), AES.block_size)
    encrypted_data = cipher.encrypt(padded_data)
    return binascii.hexlify(encrypted_data).decode()

# وظيفة لإنشاء الحمولة (payload) للعنصر
def wishlistItems_payload(id):
    g = my_pb2.Items()
    g.id = id
    serialized_data = g.SerializeToString()
    hex_data = binascii.hexlify(serialized_data).decode("utf-8")
    print("Hex Data before encryption:", hex_data)
    encrypted_data = encrypt_aes(hex_data)
    return encrypted_data

# وظيفة لإرسال العنصر
def add_item(token, encrypted_payload, item_id):
    api = "https://clientbp.ggblueshark.com/ChangeWishListItem"
    headers = {
        'User-Agent': "Dalvik/2.1.0 (Linux; U; Android 9; ASUS_Z01QD Build/PI)",
        'Connection': "Keep-Alive",
        'Accept-Encoding': "gzip",
        'Content-Type': "application/octet-stream",
        'Expect': "100-continue",
        'Authorization': "Bearer " + token,
        'X-Unity-Version': "2018.4.11f1",
        'X-GA': "v1 1",
        'ReleaseVersion': "OB48"
    }
    response = requests.post(api, data=bytes.fromhex(encrypted_payload), headers=headers, verify=False)
    print(f"Status Code for Item {item_id}: {response.status_code}")
    response_hex = response.content.hex()

# وظيفة رئيسية لتشغيل الخيوط
def main():
    token = input("ENTER JWT TOKEN: ")
    threads = []

    for item_id in items_to_send:
        encrypted_payload = wishlistItems_payload(item_id)
        thread = threading.Thread(target=add_item, args=(token, encrypted_payload, item_id))
        threads.append(thread)
        thread.start()

    # انتظار انتهاء جميع الخيوط
    for thread in threads:
        thread.join()

if __name__ == "__main__":
    main()